### ISSUE TITLE
Install pyepr through pip

### ISSUE THREAD

**Issue by crossi-T2** [avalentino/pyepr#11]
Hi,

I'm trying to install *pyepr* on a Linux CentOS release 6.5 x86_64 machine, using *pip*. After a successful installation I'm having issues to import the module:

```
$ pip -V
pip 1.3.1 from /usr/lib/python2.6/site-packages (python 2.6)
```

```
$ pip install pyepr
...
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    changing mode of /usr/bin/f2py to 755
Successfully installed pyepr numpy
Cleaning up..
```

```
$ ls /usr/lib64/python2.6/site-packages | grep pyepr
pyepr-0.9.2-py2.6.egg-info
```

```
$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyepr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyepr
```

Do you have any clue?

Thanks

Cesare

**Comment by crossi-T2** [comment]
Tried also with:

```
>>> import epr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initepr)
```

**Comment by avalentino** [comment]
Hi @crossi-T2 thanks tor reporting.
It is quite strange.
Can you please check that you have no unrelated epr.so in the local folder when you run python?

Also can you please try to install pyepr from the source tarball using setup.py (maybe in a controlled virtualenv)?

**Comment by crossi-T2** [comment]
Hi,

thank you for the feedback. Actually it behaves in the same way, even using a clean environment.
Please note that it works without issues with the version 0.8.2.

Cheers

**Comment by avalentino** [comment]
@crossi-T2 OK thanks.
I can actually reproduce the issue with python 2.6 on my box even if it seems to work perfectly fine on [Travis-CI](https://travis-ci.org/avalentino/pyepr/jobs/53556439)

All works fine with Python 2.7 instead.

> Please note that it works without issues with the version 0.8.2.

That is interesting thanks
I need to investigate a little more.

**Comment by flar** [comment]
Hi,

when I install *pyepr* on Mac OS X Yosemite using pip, I get an error when I **import epr**

> pip2.7 install pyepr
> Collecting pyepr
> Using cached pyepr-0.9.2.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): numpy>=1.5 in /usr/local/lib/python2.7/site-packages (from pyepr)
> Installing collected packages: pyepr
>  Running setup.py install for pyepr
> Successfully installed pyepr-0.9.2

Then starting python and trying to **import epr** yields

> python2.7
> Python 2.7.9 (default, Apr  7 2015, 07:58:25) 
> [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import epr
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
> ImportError: dlopen(/usr/local/lib/python2.7/site-packages/epr.so, 2): Symbol not found: _epr_clear_err
>  Referenced from: /usr/local/lib/python2.7/site-packages/epr.so
>  Expected in: flat namespace
> in /usr/local/lib/python2.7/site-packages/epr.so

Do you have any idea what is happening?

Thanks,
Ralf

**Comment by avalentino** [comment]
@flar sorry I have still not had time to investigate.
Can you please try to install pyepr from a git checkout and tall me if you area able to install it?
Please note that you should also get EPR-API sources and pass the path as parameter to the setup.py (as explained [here](http://avalentino.github.io/pyepr/html/usermanual.html#installation)).

**Comment by avalentino** [comment]
OK my tests seems to confirm that the problem is related to cython.

I was able to install pyepr successfully on an anaconda python 2.6 environment just pre-installing cython.
Having the epr module source code (epr.c) bundled in the pyepr tarball, it should not make difference if cython is installed or not.
It is still not clear to me which is the real problem.

In any case my recommendation at the moment is to use the following workaround:

* extract the source code from the pyepr tarball
* remove the src/epr.c file
* install cython
* build and install pyepr using the local cython installation

I'm working to fix the issue.
I hope to issue a new release ASAP.

**Comment by flar** [comment]
Thanks, this workaround works! Best wishes,

Ralf
